#!/bin/bash

app=lutim
domain=$1
path=$2
admin=$3
is_public=$4
final_path=/var/www/$app
port=8095

# Get first available port
sudo yunohost app checkport $port
while [[ ! $? -eq 0 ]]; do
	port=$((port+1))
	sudo yunohost app checkport $port
done


# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app
if [[ ! $? -eq 0 ]]; then
	echo "Path of the domain is not available"
	exit 1
fi

# Check user
sudo yunohost user list --json | grep -q "\"username\": \"$admin\""
if [[ ! $? -eq 0 ]]; then
	echo "Error : the chosen admin user does not exist"
	exit 1
fi

# Check /var/www/$app path is available
if [ -f $final_path ]; then
	echo "This path already contains a folder"
	exit 1
fi

# Save app settings
sudo yunohost app setting $app domain -v "$domain"
sudo yunohost app setting $app admin -v "$admin"
sudo yunohost app setting $app final_path -v "$final_path"
sudo yunohost app setting $app is_public -v "$is_public"

# Making lutim directory
sudo mkdir $final_path

# Install dependencies 
sudo apt-get update -qq >/dev/null 2>&1
yes | sudo cpan Carton
sudo apt-get install -yqq perlmagick

# Add lutim user
sudo useradd lutim
sudo groupadd lutim

# Retrieving lutim files
sudo git clone https://github.com/ldidry/lutim.git $final_path/
sudo git --git-dir=/var/www/$app/.git checkout -b proxy origin/proxy

# Installing cpan files
conff=$final_path/lutim.conf
sudo sh -c 'cd /var/www/lutim/ && sudo carton install'

# Configuring lutil with given settings
sudo cp ../conf/lutim.conf.template $conff
sudo sed -i "s,YUNOHOST_PORT,$port,g" $conff
sudo sed -i "s,YUNOHOST_CONTACT,$admin@$domain,g" $conff
secret=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{24\}\).*/\1/p')
sudo sed -i "s,YUNOHOST_SECRET,$secret,g" $conff
sudo sed -i "s,YUNOHOST_PATH,$path/g" $conff

# Copying service files
sudo cp $final_path/utilities/lutim.init /etc/init.d/lutim
sudo cp ../conf/lutim.default /etc/default/lutim
sudo chmod +x /etc/init.d/lutim
sudo chown root:root /etc/init.d/lutim /etc/default/lutim

# Configuring nginx
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
sudo sed -i "s,YUNOHOST_PATH,$path,g" /etc/nginx/conf.d/$domain.d/$app.conf
sudo sed -i "s,YUNOHOST_PORT,$port,g" /etc/nginx/conf.d/$domain.d/$app.conf

# Installing cronjobs
sudo cp ../conf/lutim_{cleanbdd,delete,stats} /etc/cron.hourly/
sudo chmod 755 /etc/cron.hourly/lutim_{cleanbdd,delete,stats}
sudo cp ../conf/lutim_watch /etc/cron.d/
sudo chmod 644 /etc/cron.d/lutim_watch

# Starting lutim service
sudo service lutim start
# Adding access for admin
sudo yunohost app addaccess $app -u $admin

# If app is public, add url to SSOWat conf as skipped_uris
if [ "$is_public" = "Yes" ];
then
	sudo yunohost app setting $app skipped_uris -v "/"
else
	sudo yunohost app setting $app protected_regex -v "$domain/$path/stats\$"
	sudo yunohost app setting $app protected_regex -v "$domain/$path/manifest.webapp\$"
	sudo yunohost app setting $app protected_regex -v "$domain/$path/\$"
	sudo yunohost app setting $app protected_regex -v "$domain/$path\$"
	sudo yunohost app setting $app protected_regex -v "$domain/$path/d/.*\$"
	sudo yunohost app setting $app protected_regex -v "$domain/$path/m/.*\$"
fi

sudo chown lutim:lutim -R $final_path
sudo chmod g+rx $final_path
sudo service lutim restart

# again cause some new files are created
sudo chown lutim:lutim -R $final_path
sudo chmod g+rx $final_path

sudo service nginx restart
sudo yunohost app ssowatconf